### ISSUE TITLE
network app database migration errors on first play

### ISSUE THREAD

**Issue by axilleas** [satnogs/satnogs-ansible#11]
\cc @comzeradd 

The first time the `playbook/network{,-dev}.yml` is ran I get the following error:

```
failed: [satnogs] => {"cmd": "python manage.py migrate --noinput --settings=network.settings.stage", "failed": true, "path": "/var/www/satnogs/network/dev/venv/bin:/sbi
n:/bin:/usr/sbin:/usr/bin", "state": "absent", "syspath": ["/home/vagrant/.ansible/tmp/ansible-tmp-1434015853.06-147979309317235", "/usr/lib64/python27.zip", "/usr/lib6
4/python2.7", "/usr/lib64/python2.7/plat-linux2", "/usr/lib64/python2.7/lib-tk", "/usr/lib64/python2.7/lib-old", "/usr/lib64/python2.7/lib-dynload", "/usr/lib64/python2
.7/site-packages", "/usr/lib/python2.7/site-packages"]}
msg: stdout: Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, allauth, api, avatar, rest_framework, crispy_forms
  Apply all migrations: authtoken, account, users, sessions, admin, sites, auth, contenttypes, base
Synchronizing apps without migrations:
  Creating tables...
    Creating table avatar_avatar
    Running deferred SQL...

:stderr: Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
    return self.cursor.execute(query, args)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/satnogs/network/dev/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1005, "Can't create table 'network_dev.#sql-39d3_36' (errno: 150)")
```

Consecutive runs don't error out.

**Comment by comzeradd** [comment]
This should not be a problem anymore. Migrations have been squashed on Network app.
